### PR TITLE
Drop obsolete reference to build status on travis-ci.org

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Comment by msekletar** [comment]
We need to merge #16 first and then retrigger the CI.

**Review by jamacku — APPROVED** [review]
LGTM

[`.travis.yml`](https://github.com/msekletar/prefixdevname/blob/main/.travis.yml) can be also dropped

**Comment by msekletar** [comment]
@jamacku good point!

**Review by jamacku — APPROVED** [review]

**Comment by jamacku** [comment]
Blocks #8

**Pull request merged**
